### ISSUE TITLE
Transmission can download to SD card,but Aria2 can't 

### ISSUE THREAD

**Issue by jakiro6708** [devgianlu/Aria2Android#126] opened 2023-04-12 11:34 UTC
If insert a SD card to phone,and set aria2 download path to SD card,it will fail,but transmission can download to SD card

**Comment by devgianlu** [comment] 2023-04-21 09:48
Duplicate of https://github.com/devgianlu/Aria2App/issues/260

**Closed as completed by devgianlu** 2023-04-21 09:48 UTC
Labels: duplicate
